spring.application.name=car-rental-api-spring-boot-project


server.port=9999

# MySQL Database
spring.datasource.url=jdbc:mysql://localhost:3306/car-rental-app
spring.datasource.username=root
spring.datasource.password=Shan9565
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true